theme: jekyll-theme-cayman
title: Tensegrity Robotics
description: This webpage is meant to list papers related to Tensegrity Robotics, and provide links to tutorials and workshops, and pointers to existing Tensegrity Projects.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  parse_block_html: true
include:
  - CONTRIBUTING.md
  - index.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
